### ISSUE TITLE
checklist -> branch development_check

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/web3_proxy#26]
- [ ] get 1 branch with all functionality as done so far
- [ ] check v code exists to call all openrpc calls in web3 proxy
- [ ] make sure the code (SAL) is clear and easy to understand

## why

- allows us to see how far we got

**Comment by DylanVerstraete** [comment]
@despiegk can we close this as completed?
